### ISSUE TITLE
Chaining with responsive variants

### ISSUE THREAD

**Issue by nomadoda** [unlight/tailwind-ie-variant#15]
Thanks for this plugin!

I'm not able to override responsive variants. For example, I want to hide a button on IE and on mobile, I'd expect to write:

```html
<button class="hidden md:block md:ie:hidden"></button>
```

Unfortunately the chained selector doesn't produce any style.

**Comment by unlight** [comment]
Please, read https://github.com/unlight/tailwind-ie-variant#usage

You need add `postcss-nesting plugin`

**Comment by nomadoda** [comment]
I was using `postcss-nested`. Trying with `postcss-nesting` and getting same results. I'm actually using a `_` separator and  it's rather looking like this:

```html
<button class="hidden md_block md_ie_hidden"></button>
```

**Comment by unlight** [comment]
@nomadoda 
Could you share your postcss config ?

**Comment by nomadoda** [comment]
My original `.postcssrc`:

```json
```

**Comment by nomadoda** [comment]
I've created a repo to demonstrate, https://github.com/nomadoda/tailwind-ie-variant-test. I'm not sure why it's not working, the generated css looks fine?

```css
.table {
  display: table;
}
.hidden {
  display: none;
}
@media (min-width: 768px) {
  .md_block {
    display: block;
  }
  .md_hidden {
    display: none;
  }
  @media (-ms-high-contrast: none), screen and (-ms-high-contrast: active) {
    .md_ie_block {
      display: block;
    }
    .md_ie_hidden {
      display: none;
    }
  }
}
```

**Comment by nomadoda** [comment]
It seems like `postcss-nesting` doesn't "unnest" media queries (by default at least) and nested media queries are not supported on IE.

**Comment by unlight** [comment]
So, to make it work, we need css result like:
```css
.table {
  display: table;
}
.hidden {
  display: none;
}
@media (min-width: 768px) {
  .md_block {
    display: block;
  }
  .md_hidden {
    display: none;
  }
}

@media (min-width: 768px) and (-ms-high-contrast: active),
  (-ms-high-contrast: none) {
  .md_ie_block {
    display: block;
  }
  .md_ie_hidden {
    display: none;
  }
}
```

**Comment by nomadoda** [comment]
Yes, I think so. It seems like something `postcss-nesting` or `postcss-nested` should be able to do, but I haven't succeeded.

**Comment by unlight** [comment]
Have you tried https://github.com/postcss/postcss-nested#unwrap unwrap
option for postcss-nested?
I tried to find some postcss plugins related to this issue
https://github.com/giuseppeg/postcss-nest-atrules
https://github.com/Semigradsky/postcss-nested-media-queries

**Comment by nomadoda** [comment]
I'm at wits' end now. I've added an issue to `postcss-nested` https://github.com/postcss/postcss-nested/issues/141

**Comment by unlight** [comment]
@nomadoda 

Looks like https://github.com/Semigradsky/postcss-nested-media-queries is what you need.

```
{
  "plugins": {
    "tailwindcss": {},
    "postcss-nesting": {},
    "postcss-nested-media-queries": {}
  }
}
```
Result:

```css
.table {
	display: table;
}
.hidden {
	display: none;
}
@media (min-width: 768px) {
	.md_block {
		display: block;
	}
	.md_hidden {
		display: none;
	}
}
@media (-ms-high-contrast: none),
	(min-width: 768px) and screen and (-ms-high-contrast: active) {
	.md_ie_block {
		display: block;
	}
	.md_ie_hidden {
		display: none;
	}
}

```
Will it work for you. Could you check?

The problem is `postcss-nested-media-queries` is not published, you can try to contact the author or build and publish it by yourself.
